FROM openjdk:8u181-jdk-alpine

RUN mkdir -p /opt/iot/plugin / && chmod -R 777 /opt/

COPY ./target/iot-bridge-sample-tcp-protocol-1.1.3-with-deps.jar /opt/iot/plugin

USER root

CMD ["java", "-jar", "/opt/iot/plugin/iot-bridge-sample-tcp-protocol-1.1.3-with-deps.jar", "run"]
